export { default as OrphanagesMap } from './orphanages-map/orphanages-map'
export { default as OrphanageDetails } from './orphanage-details/orphanage-details'
export { default as CreateOrphanageOnMapPosition } from './create-orphanage/create-orphanage-on-map-position/create-orphanage-on-map-position'
export { default as CreateOrphanageFormStepOne } from './create-orphanage/create-orphanage-form-step-one/create-orphanage-form-step-one'
export { default as CreateOrphanageFormStepTwo } from './create-orphanage/create-orphanage-form-step-two/create-orphanage-form-step-two'
